name: remote ssh command
on:
  push:
    branches:
      - master
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      
      - name: SSH into dedicated host and "make prod"
        uses: appleboy/ssh-action@master
        env:
          DOT_ENV_FILE: ${{ secrets.DOT_ENV_FILE }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEDI_DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          envs: DOT_ENV_FILE
          script: |
            echo "starting production deploy on $(whoami)@$(hostname) \n\n\n ------------------"
            echo "stopping current docker compose stack:"
            cd cog-x && make down && cd ~
            echo "removing old code and re-cloning repo:"
            rm -rf cog-x && git clone git@github.com-cog:paulmikulskis/cog-x.git
            echo "hydrating .env"
            cd cog-x && echo "$DOT_ENV_FILE" > .env
            echo "running yarn install"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install 16 && nvm use 16 && yarn install
            echo "B00TING!"
            make prod
            echo "healthcheck:"
            curl --connect-timeout 5 "127.0.0.1:15000/"