name: production deploy of cog
on:
  push:
    branches:
      - master
jobs:
  Deploy:
    name: Production Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      
      - name: Build and push to registry.yungstentech.com
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.yungstentech.com/cog-x:latest

      - name: SSH into dedicated host docker run
        uses: appleboy/ssh-action@master
        env:
          DOT_ENV_FILE: ${{ secrets.DOT_ENV_FILE }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEDI_DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          envs: DOT_ENV_FILE
          script: |
            rm -rf cog-x && git clone git@github.com-cog:paulmikulskis/cog-x.git
            echo "hydrating .env"
            cd cog-x && echo "$DOT_ENV_FILE" > .env
            docker compose down -v
            docker image rm --force registry.yungstentech.com/cog-x:latest
            docker compose -f docker-compose-prod.yml up -d --force-recreate